name: "Master Job for Nested Jobs Example"

on:
  push:
    branches:
      - nested-workflows
      - nested-workflows-WIP

jobs:
  master_job:
    name: Run master job
    runs-on: ubuntu-latest

    steps:
      - name: Master Step 1
        run: echo Master Step 1
      - name: Master Step 2
        run: echo Master Step 2